#!/usr/bin/env bash
set -eou pipefail

VERSION=$1
GHCR_REGISTRY="ghcr.io/portfolio-solver-platform"
DOCKERHUB_REGISTRY="jobork"
IMAGE_NAME="parasol"
GIT_SHA=$(git rev-parse --short HEAD)

IMAGE_BASE_MAIN="$GHCR_REGISTRY/$IMAGE_NAME"
CACHE_URI="$IMAGE_BASE_MAIN:latest"

echo "Building and pushing main Docker image ($IMAGE_BASE_MAIN) to GHCR..."
docker buildx build --push \
  --cache-from="type=registry,ref=$CACHE_URI" \
  -t "$IMAGE_BASE_MAIN:$VERSION" \
  -t "$IMAGE_BASE_MAIN:latest" \
  -t "$IMAGE_BASE_MAIN:$GIT_SHA" \
  .

IMAGE_BASE_ELIGIBLE_GHCR="$GHCR_REGISTRY/$IMAGE_NAME-challenge-eligible"
IMAGE_BASE_ELIGIBLE_HUB="$DOCKERHUB_REGISTRY/$IMAGE_NAME-challenge-eligible"

echo "Building and pushing eligible challenge image to GHCR and Docker Hub..."
docker buildx build --push \
  --build-arg PARASOL_TEMPLATE=parasol-challenge-eligible.msc.template \
  --cache-from="type=registry,ref=$CACHE_URI" \
  -t "$IMAGE_BASE_ELIGIBLE_GHCR:$VERSION" \
  -t "$IMAGE_BASE_ELIGIBLE_GHCR:latest" \
  -t "$IMAGE_BASE_ELIGIBLE_GHCR:$GIT_SHA" \
  -t "$IMAGE_BASE_ELIGIBLE_HUB:$VERSION" \
  -t "$IMAGE_BASE_ELIGIBLE_HUB:latest" \
  -t "$IMAGE_BASE_ELIGIBLE_HUB:$GIT_SHA" \
  .

IMAGE_BASE_INELIGIBLE_GHCR="$GHCR_REGISTRY/$IMAGE_NAME-challenge-ineligible"
IMAGE_BASE_INELIGIBLE_HUB="$DOCKERHUB_REGISTRY/$IMAGE_NAME-challenge-ineligible"

echo "Building and pushing ineligible challenge image to GHCR and Docker Hub..."
docker buildx build --push \
  --build-arg PARASOL_TEMPLATE=parasol-challenge-ineligible.msc.template \
  --cache-from="type=registry,ref=$CACHE_URI" \
  -t "$IMAGE_BASE_INELIGIBLE_GHCR:$VERSION" \
  -t "$IMAGE_BASE_INELIGIBLE_GHCR:latest" \
  -t "$IMAGE_BASE_INELIGIBLE_GHCR:$GIT_SHA" \
  -t "$IMAGE_BASE_INELIGIBLE_HUB:$VERSION" \
  -t "$IMAGE_BASE_INELIGIBLE_HUB:latest" \
  -t "$IMAGE_BASE_INELIGIBLE_HUB:$GIT_SHA" \
  .
