#!/usr/bin/env bash
set -eou pipefail

VERSION=$1
REGISTRY="ghcr.io/portfolio-solver-platform"
IMAGE_NAME="parasol"

IMAGE_BASE="$REGISTRY/$IMAGE_NAME"
GIT_SHA=$(git rev-parse --short HEAD)

IMAGE_URI="$IMAGE_BASE:$VERSION"
IMAGE_URI_HASH="$IMAGE_BASE:$GIT_SHA"
IMAGE_URI_LATEST="$IMAGE_BASE:latest"

echo "Building and pushing Docker image ($IMAGE_URI)..."
docker buildx build --push -t "$IMAGE_URI" -t "$IMAGE_URI_LATEST" -t "$IMAGE_URI_HASH" --metadata-file build-metadata.json .
