name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
      packages: write
    with:
      update_image_cache: true

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
