name: Renovate
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [main]
env:
  RENOVATE_VERSION: 43.80.0 # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate app token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        id: app-token
        with:
          app-id: ${{ vars.INFRASTRUCTURE_BOT_APP_ID }}
          private-key: ${{ secrets.INFRASTRUCTURE_BOT_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@68a3ea99af6ad249940b5a9fdf44fc6d7f14378b # v46.1.6
        with:
          renovate-version: ${{ env.RENOVATE_VERSION }}
          configurationFile: renovate-config.js
          token: ${{ steps.app-token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
